### ISSUE TITLE
Set Preferences

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#202]
### Desired Behaviour (for feature requests only)

As described in [acceptance test](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/data_curator/set-preferences.feature)

See https://github.com/nathanbuchar/electron-settings/blob/master/README.md

~~Adding CSV Dialect support may influence Open, Save, Export behaviour.~~

**Comment by Stephen-Gates** [comment]
May also capture CKAN API for duration of the session (or store securely)

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Just trying to get sense of what are specific requirements here.
This work is about persisting permanent settings to...a file?...so that every time a user opens Data Curator, certain properties are already set (correct?)

So far I think the priority list is:
- licenses (at package level only?)
- contributors
- enum constraint limit (time permitting)
- dialect (ie: changing defaults set by frictionless - time permitting for, testing save, export, etc)

Am I on the right track?

**Comment by Stephen-Gates** [comment]
1. Correct
2. Settings set default values but these can still be changed in Properties panel
3. User interface 
  - left
  - menu item varies based on OS. See placeholder in menu file
  - no toolbar
  - See keyboard shortcuts file
4. See acceptance test

**Comment by mattRedBox** [comment]
Once package properties for licenses and contributors are in place, these are 'preferenced' over anything from settings.
