### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by joelgombin** [ODIQueensland/data-curator#247]
Is there anyway to use data curator on a Linux distro (apart from using a VM, wine etc.)?

**Comment by Stephen-Gates** [comment]
Hi @joelgombin, 
Developing a Linux distribution is not in our plans. All I can suggest is exploring the [Electron docs](https://electronjs.org/docs) for clues on how you could do the build on your computer. If you work it out, a PR is very welcome  :-)

**Comment by chris48s** [comment]
In principle electron apps are cross-platform. If I check out the repo on linux the application will run in dev mode:

```
git clone https://github.com/ODIQueensland/data-curator.git
cd data-curator/
yarn install
yarn run dev
```

Given the application launches under linux, there shouldn't be much of a barrier to producing a linux binary of some description, especially given data curator removes the dependency on travelling ruby/csvlint (which was one of the things that required some fiddling to get the builds to work cross-platform in comma chameleon). Attempting to run`yarn build` on linux fails with `Error: Icon set directory /bla/bla/bla/build/icons doesn't contain icons`. It may be that adding an icon  in the correct format is the only thing you need to do in order to build a linux binary.

**Comment by Stephen-Gates** [comment]
Great! Thanks for investigating @chris48s.

**Comment by chris48s** [comment]
Yep - I've just checked out the latest version. `yarn build` now runs correctly. :+1: By default it produces an AppImage, but it seems like its fairly easy to configure `electron-builder` to produce other package formats: https://www.electron.build/configuration/linux

I'm not sure on your process for packaging a release, but given you've got a build process which can build a linux binary it might be nice to include one in future releases.

**Comment by Stephen-Gates** [comment]
see also #830
