### ISSUE TITLE
CSV Dialect support for header and delimiter

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#282]
### Desired Behaviour (for feature requests only)

CSVDialect header and delimiter properties are written to the datapackage.json

Delimiter will be determined by the saved file format (tab, comma, semi-colon separated)
(related #218)

Header will be determined by Table property. Take care in UI design to avoid confusion between freezing header row on screen and export value.
(related #259)

**Comment by Stephen-Gates** [comment]
Note conversation about CSV dialect at URL https://github.com/frictionlessdata/specs/issues/561

**Comment by mattRedBox** [comment]
Ok @Stephen-Gates 
So we're adding something like:
```
"dialect": {
      "delimiter": ";",
      "header": true
    }
```
to the package.json on export (And also support on import).

The header here obviously needs to be tracking what's happening with the header rows in gui - but considering we force the package to have header rows anyway this should be ok.

And understood about delimiter.

For the frictionless conversation, I guess from our side this is important more for 'import' of datapackage.json atm, so that we also support a "string" showing url-or-path, if this is present instead of an object.

**Comment by Stephen-Gates** [comment]
@mattRedBox 

If the user saves a tab separated value file and then exports a data package, 
- the datapackage.zip will contain data.tsv
- the datapackage.json will
  - have the `delimiter` set
  - `format` and `mediatype` set behind the scenes -  https://frictionlessdata.io/specs/data-resource/#optional-properties

**Comment by Stephen-Gates** [comment]
see also https://discuss.okfn.org/t/correct-use-of-csv-dialect/5573/2?u=stephen

**Comment by mattRedBox** [comment]
yep we're just grabbing what frictionless makes available on use of libraries, similarly using the dialect object to hold all 
and translating the different names used by node.js csv when used or the format options made available from save and open dialogs.
