### ISSUE TITLE
Validate RDF Type property as a URI

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#314]
### Current Behaviour (for problems)
RDF Type is not validated

### Expected Behaviour
[RDF Type](https://frictionlessdata.io/specs/table-schema/#rich-types) must be a URI

### Your Environment

* Data Curator version: 0.7.0
* Operating System and version:  macOS High Sierra 10.13.1

**Comment by mattRedBox** [comment]
My understanding is that the rdf type can be any kind of URI, not always just a URL? - I think that this might be extremely hacky and difficult to do.
I notice that in the referring document from the spec, that the standard changed from URI to [IRI](https://tools.ietf.org/html/rfc3987#section-3.2.1), which seems even more generic.
Are we expecting that rdf classes are always some type of url, rather than iri?

**Comment by Stephen-Gates** [comment]
Let's just validate as a URL for the moment

**Comment by Stephen-Gates** [comment]
I didn’t see an error message with this validation when I quickly tested it. Is there one?
