### ISSUE TITLE
Some Latin characters not displayed correctly in data table

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#318]
### Current Behaviour (for problems)

This [data](https://data.qld.gov.au/dataset/conservation-status-of-queensland-wildlife/resource/1c8b4859-31a4-42e7-8e63-b7cf125d4321) contains special characters e.g. Latin Small Letter U with diaeresis

These are rendered correctly in Excel... 
![image](https://user-images.githubusercontent.com/9379524/33862686-b47ad594-df2f-11e7-9d3c-e1474b7ec66f.png)

... but not in Data Curator

![image](https://user-images.githubusercontent.com/9379524/33862652-919d74fa-df2f-11e7-94ba-19682e0e5d93.png)
 
### Expected Behaviour

Extended Latin characters are rendered correctly 

### Your Environment

* Data Curator version: 0.7.0 
* Operating System and version: e.g. Windows 7

**Comment by Stephen-Gates** [comment]
This make be related to how CKAN downloads the data rather than Data Curator.

ISO8601 dates on CKAN

<img width="381" alt="screenshot 2018-02-10 10 11 06" src="https://user-images.githubusercontent.com/9379524/36058537-c6fb7a20-0e6e-11e8-8a84-94235e4f9528.png">

Get converted to 

<img width="243" alt="screenshot 2018-02-10 14 30 30" src="https://user-images.githubusercontent.com/9379524/36058545-01f0dc4c-0e6f-11e8-8aa2-9b476497a15b.png">

Same for `-` and `'` characters

Reported via data.qld.gov.au

**Comment by mattRedBox** [comment]
I've been able to copy foreign characters into Data-Curator without issue.
Not sure I understand the date issue - has nothing to do with characters.

**Comment by Stephen-Gates** [comment]
@louisjasek this appears to be a CKAN issue. Can we close and you address from your side?

**Comment by louisjasek** [comment]
@Stephen-Gates 

If it is a problem with CKAN, it is probably more probable that I won't get to address this from my side - or at least not in the shorter term.

Are you able to write a short summary of the issue for users? E.g. what is the issue, when does it occur, what are the special characters affected and how can a user still use data curator if their data has special characters (if there is a way around it).

I'd be happy to close it then.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Just to demonstrate another test that it is the server that perhaps isn't encoding the dataset correctly.
From command-line:

1.  Using curl
- **curl: transfers a url (note: it has no means to alter the character-encoding)**
`curl "https://data.qld.gov.au/dataset/a951ca57-a119-40ad-9530-e9c204222e8a/resource/1c8b4859-31a4-42e7-8e63-b7cf125d4321/download/species.csv"`

**Abridged Output**:
`Taxon_Id,Kingdom,Class,Family,Scientific_name,Common_name,Taxon_author
706,animals,amphibians,Limnodynastidae,Adelotus brevis,tusked frog,"(G?nther, 1863)"`

2. Using curl + another tool to perform character conversion:
- **curl: transfers a url (note: it has no means to alter the character-encoding)**
- **iconv: performs character set conversion**
`curl "https://data.qld.gov.au/dataset/a951ca57-a119-40ad-9530-e9c204222e8a/resource/1c8b4859-31a4-42e7-8e63-b7cf125d4321/download/species.csv" | iconv -f iso8859-1 -t utf-8`

**Abridged Output**:
`Taxon_Id,Kingdom,Class,Family,Scientific_name,Common_name,Taxon_author
706,animals,amphibians,Limnodynastidae,Adelotus brevis,tusked frog,"(Günther, 1863)"`

The above shows that there is an issue with the server-side encoding of the data (as curl does not handle character-sets - another tool is needed for this, shown in example 2)

I've looked into what we could do. There are tools in node.js to guess character sets, and to convert them - unfortunately they're not as trivial to setup as the command-line example, above (this is due to the nature of characters being read in, in chunks,  which may accidentally split a complex character, before conversion).

https://github.com/ODIQueensland/data-curator/issues/387 concerns slow performance - part of what I'd like to investigate here is look at how streams might better handle the legacy code which converts all of data to string in memory. We could add a menu item perhaps (rather than doing on the fly, in case the conversion is not ideal) for converting data here as the logic (for handling incoming data) is in the same place.

**Comment by Stephen-Gates** [comment]
thanks @mattRedBox. @louisjasek perhaps Ray could investigate:

- using UTF8
- not converting dates either in the data preview and/or download.

**Comment by louisjasek** [comment]
@Stephen-Gates I'll have a chat to Ray, but I don't think we can address this from our side in the short term. Can you write a short description of the issue for users before we close this? See more details of what to include from my post yesterday.

**Comment by Stephen-Gates** [comment]
Known issue will be documented at 

https://ask.theodi.org.au/t/known-issue-some-data-downloaded-from-ckan-doesnt-display-correctly/535

**Comment by Stephen-Gates** [comment]
@mattRedBox is this relevant https://github.com/frictionlessdata/datapackage-py/pull/212

**Comment by Stephen-Gates** [comment]
@louisjasek any objections to closing this issue?

**Comment by louisjasek** [comment]
See my question from #476 - same as this one
