### ISSUE TITLE
Performance on large tables is slow

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#387]
### Desired Behaviour

When editing a csv with 150,000 rows performance is ver slow. Explore option to improve performance.

Review HandsOnTables : 
- configuration option https://docs.handsontable.com/0.35.0/tutorial-performance-tips.html
- issues https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Core%3A+performance%22

**Comment by Stephen-Gates** [comment]
This may be helpful https://forum.handsontable.com/t/how-to-implement-a-lazy-loading-algorithm/1828/3?u=stephen.gates

**Comment by mattRedBox** [comment]
Lot of investigation here, but with small code change in the end :P
Apparently by enabling deselect previously, a move back to a table would then mean that visibleRowCount would then revert to the total number of rows. 
Setting outsideClickDeselects to true, ensures that this count remains within scollable area.

There could be some further work to stream data on load to see if this helps with giving access to the table earlier ie: load some data and show the table, while the remainder continues to load in the background in non-scrollable area - but 20 000 rows in several seconds seems OK to me (at least for now).

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates, @louisjasek
The fix for toggling between tabs, has revealed a shortcoming in the app presentation ({outsideClickDeselects: true}), in that when moving outside of the spreadsheet, the cell(s) are now deselected which, while the app is aware of say, what column it's in, the user cannot see the cell/row/column highlighted. 

At the moment, I haven't found a solution to marry a fix for both this and the performance issue, but - unless you want me to leave it for now - I can keep looking at this during the next sprint.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates , @louisjasek
Just an update:
I've isolated why I think I've found where the problem lies within handsontable app. When 
`outsideClickDeselects: false`, which we need to allow the user to continue to see which cell is highlighted when making updates in other menus,
there is logic within the handsontable, that uses this setting to destroy the editor for that handsontable:
I've raised the issue with the developers there, which you can track here:
[https://github.com/handsontable/handsontable/issues/4932](https://github.com/handsontable/handsontable/issues/4932)
Whatever their response, knowing that this is the cause, may help me in providing a workaround in the interim.

**Comment by Stephen-Gates** [comment]
Perhaps wait for a reply, then assess next steps.
