### ISSUE TITLE
escapeChar is mutually exclusive with quoteChar 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#463]
### Current Behaviour 

I saved a TSV and made a data package. The CSV dialect produced was:

```
"dialect": {
                "delimiter": "\t",
                "quoteChar": "\"",                  # can't have this
                "header": true,
                "doubleQuote": true,
                "lineTerminator": "\r\n",
                "escapeChar": "\\",                 # and this
                "skipInitialSpace": true,
                "caseSensitiveHeader": false
            }
```

### Expected Behaviour

The [specs](https://frictionlessdata.io/specs/csv-dialect/#specification) say escapeChar is mutually exclusive with quoteChar, so we shouldn't write both. We should drop `escapeChar`.

### Your Environment

* Data Curator version: 0.10.0 dev
* Operating System and version: e.g. macOS High Sierra 10.13.3

**Comment by mattRedBox** [comment]
We don't explicitly create those fields, so it may be an issue from tableschema.js

**Comment by Stephen-Gates** [comment]
I thought we set the values based on what happens in our app. Are these values inferred?

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
At the moment, based on previous tickets we just add quoteCharacter and delimiter.
I've gone through our code where we add quote character and removed and I can still see both quoteCharacter and escapeCharacter coming through when we call Resource.commit(). So yes, I believe that this is a ticket for datapackage-js

**Comment by Stephen-Gates** [comment]
Thanks @mattRedBox  can you add to https://github.com/frictionlessdata/datapackage-js/issues ?

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
@roll is aware:
https://github.com/frictionlessdata/datapackage-js/issues/102

**Comment by Stephen-Gates** [comment]
Perhaps we could consider a PR to datapackage.js - change seems minor?

**Comment by mattRedBox** [comment]
consider effort here in determining whether to include.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
In going through the datapackage-js unit tests, I need to check with you about business logic we expect here.

According to the [spec](https://frictionlessdata.io/specs/csv-dialect/#specification), and within the code we can easily ensure (as in their python code)
quoteChar (" is default) is set
and no escapeChar set (this is the default).

And this also works if the user wants to set the quoteChar.
However what happens if the user wants to set the escapeChar? Atm, from what I can see the code doesn't support this (as quoteChar trumps so escapeChar won't appear)
ie: should the user be able to specify an escapeChar? And if so, should this then remove the quoteChar?

**Comment by Stephen-Gates** [comment]
@mattRedBox I see two parts:

1. When we export, only write the `quoteChar`
2. When we import, only import [dialects we can handle](https://github.com/ODIQueensland/data-curator/issues/394); otherwise import error.

Does that help?

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
We can handle export and import I think, the problem will be the validation, but will wait and see if any movement from [datapackage-js](https://github.com/frictionlessdata/datapackage-js/pull/104)

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Think this might be OK :) to include in release
