### ISSUE TITLE
Errors found but not shown in Errors window

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#617]
### Current Behaviour 

<img width="1439" alt="screenshot 2018-03-29 06 22 32" src="https://user-images.githubusercontent.com/9379524/38054231-b4be65aa-3319-11e8-82ad-cd6f0526dc1f.png">

### Expected Behaviour

errors shown in window

* Data Curator version: 0.13.0
* Operating System and version:  macOS High Sierra 10.13.3

**Comment by Stephen-Gates** [comment]
Results inconsistent 

<img width="1224" alt="screenshot 2018-03-29 06 39 49" src="https://user-images.githubusercontent.com/9379524/38055083-11a45b06-331c-11e8-9b5d-47b0a06b8971.png">

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
atm, When the button is clicked:
1. the 'Home' window sends a message to main to open the Errors Window
2. (depends on 1.) once the Errors window opens, it sends a message to Home asking for the errors to be sent
3. (depends on 2.) the Home window receives this and sends the error messages to the Errors Window
 
It could be that sometimes (due to asynchronous nature of the app) that 1 and 2 are being sent too quickly before step 3. is ready.
I've adjusted step 1 to try to ensure that it doesn't fire before step 3. is ready to listen.
It's only a guess though as I can't seem to replicate this consistently either.
