### ISSUE TITLE
Find and Replace user interface refinement 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#706]
Adjust find and replace button sizes to align nicely 

<img width="874" alt="screenshot 2018-04-19 06 43 01" src="https://user-images.githubusercontent.com/9379524/38957360-b417085c-439d-11e8-8aa7-0548628f5cff.png">

Probably add padding to <|> buttons

### Your Environment

* Data Curator version: 0.14.0
* Operating System and version:  macOS High Sierra 10.13.4

**Comment by louisjasek** [comment]
Potentially yes would be better, but not a major concern for me.

@Stephen-Gates did you create an issue to include some warning text about the undo functionality not working in find and replace?

**Comment by Stephen-Gates** [comment]
Good point. I’ll generalise the issue title so we can cover it here

**Comment by Stephen-Gates** [comment]
- [ ] include some warning text about the undo functionality not working in find and replace?
- [ ] fix button alignment
- [ ] adjust panel title

**Comment by mattRedBox** [comment]
@Stephen-Gates 
What's the expectation with Undo -> when replace is fixed, I would expect that because we're deferring to handsontable, there will be some undo functionality here. 
But the replaceAll, for performance reasons, we actually clobber the entire array set (rather than using handsontable set for each cell, which would be far slower), so there would be no undo here.
I can provide the warning when the user hits replace/all with warning and prompt to proceed with OK/Cancel button?

**Comment by Stephen-Gates** [comment]
Perhaps like you have with other property data entry errors, when a user adds a value in the replace text, some red text is displayed warning that "Replacing values cannot be undone"

<img width="367" alt="screenshot 2018-05-02 12 36 18" src="https://user-images.githubusercontent.com/9379524/39502765-70e0086e-4e05-11e8-97f1-0dceea934869.png">

**Comment by mattRedBox** [comment]
OK will have a look and see what I can do
