### ISSUE TITLE
Find and Replace keyboard shortcuts are not implemented 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#738]
[Find](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/find/find.feature) and [Replace](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/find/replace.feature) keyboard shortcuts are not implemented.

Keyboard shortcuts are commented out in [KeyboardHelp.vue](https://github.com/ODIQueensland/data-curator/blob/develop/src/renderer/components/KeyboardHelp.vue) and are also in [Main.js](https://github.com/ODIQueensland/data-curator/blob/develop/src/main/menu.js)

Related to #707

**Comment by Stephen-Gates** [comment]
@mattRedBox my apologies, I specified shift + command +G for Find Previous but that's already taken.

How about option + command + G?

**Comment by Stephen-Gates** [comment]
Alt = Option on macOS 👍

**Comment by louisjasek** [comment]
I'm finding that this shortcut moves 3 rows instead of 1. For example, I might be on row 1 in a column, then hit the short cut and it moves to row 4 instead of row 2. Seems to be the same for both find and replace. I'm not too concerned about it - certainly not priority over other issues, but thought I'd make a note in case it is a very quick fix. @Stephen-Gates are you getting the same result?

**Comment by mattRedBox** [comment]
Hi @louisjasek 
I'm having trouble replicating this - what OS are you using and do you have some example data?
Haven't updated Shift to Alt yet, so when able to, will push this into development build for next release.

**Comment by louisjasek** [comment]
I'm on macOS Sierra 10.12.6

However, I just went to try again and it is working now. It was definitely skipping 3 rows before though - let's leave it for now but keep an eye on it.
