### ISSUE TITLE
Add test coverage badge and link to test report

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#802]
Add test coverage badge to readme and link from the badge the test report (potentially published on github pages)

**Comment by mattRedBox** [comment]
All boilerplate in place - just need to overcome ci time limit of 60 mins

**Comment by Stephen-Gates** [comment]
Do the tests take that long to run?

**Comment by mattRedBox** [comment]
@Stephen-Gates 
That's for everything (ie: all tests):
includes the vm setup, node installation,
but yes remembering that there are hundreds of scenarios in there (including ones not defined yet),
and that there's time to bring up the app and wait for elements to be present, 60 mins or more not unusual for everything.

**Comment by mattRedBox** [comment]
I'll look at this on and off now that we're at a close (as executing large number tests doesn't take much - just going back every now and then to see if it worked)
- we can get around this in Travis I think as it allows for common build and then running matrix in parallel (have done it before in java so probably also available for node.js) - but this would be testing only on mac osx.
- problem is appveyor don't allow parallel execution on OS plan :( But there might be other ways to do this (and would prefer to have tests running regularly in some way on Windows as this includes large number of users for this app).

**Comment by Stephen-Gates** [comment]
@mattRedBox Should we close this issue and make another for the time issue so the milestone can be closed?

**Comment by mattRedBox** [comment]
hi @Stephen-Gates 
yes sounds good - as we have what we need to create badges now - I'm thinking for the timeout/lack of concurrent builds in appveyor problem (as there doesn't seem to be another way with appveyor) that we:
- lock down master so that it can only receive pull requests and put github 'checks' in place (already set some of this up)
- when pushing to master the checks will be the code linter and the tests run, so that:

- run unit and acceptance tests in Travis (the OS license allows us to cache builds, run tests in parallel, etc so time shouldn't be an issue)
- when the Travis tests run successfully, run script which checks out branch for each test feature/folder and commit
- have a generic appveyor config in all branches, so that when these branches are created and committed they trigger an appveyor build -> this will cause a significant number of separate jobs against appveyor, so will potentially take even longer this way (unless I find out that we can cache an appveyor build somehow) - as each test will run sequentially, but it means that we can get around the timeout/concurrency issue by running multiple appveyor builds (but sequentially)

The final step then would be for successful tests to somehow trigger:
- the tagging after all of these  run successfully

The artifacts build of course would still apply only to a created tag.

- should be about half a day to a day's work -> mostly just to wait for multiple builds and tests to run and iron out any gotchas.

**Comment by mattRedBox** [comment]
Note:
https://blog.travis-ci.com/2018-10-11-windows-early-release
Might be simpler to wait for beta-testing (ie: others, before introducing here) and scrap appveyor for travis (more flexibility for matrix jobs)
