### ISSUE TITLE
Impossible date passes validation

### ISSUE THREAD

**Issue by drchriscole** [ODIQueensland/data-curator#842]
A column set as 'Date' type with the default format (e.g. YYYY-MM-DD) accepts the string '2022-22-22' as valid. Clearly this isn't a valid date.

This is in version 1.0.0 on MacOS 10.13.6

**Comment by mattRedBox** [comment]
Thanks for raising this @drchriscole.
I was able to replicate this too - I'll have a look at what we can do here.

**Comment by mattRedBox** [comment]
Hi @drchriscole 
I'm assuming here that the issue arises when you click the toolbar button: 'Validate' or the menu item: 'Validate Table'
I've had a look at the underlying libraries we use to validate the date and from what I can see the use here is to use the format: 'any', rather than 'default'.
'Any' will validate the date as is, so a validation will fail in the use case you have provided.
'Default' will attempt to convert all to ISO8601. So in your case, the library returns: 2023-10-22 (note it has 'wrapped-around' the extra months here, adding them to the year) - we just don't pass back the converted value, so as not to interfere with the data provided by the user.
At this stage, I'm not sure what message/warning we can display with the view setup we already have, but I think most users would be in a similar position to yours, and would not want dates to be attempted to auto-convert, and would want a validation error for similar values. 

So for now, I will look at changing the 'default' format for date' to 'any' - that way a user would normally have the validation fail, when they select 'date'.
I'm also looking at doing the same for our 'Guess' function, but just because I'm unsure of the why here,  I have also raised a question with one of our main underlying libraries that handles this for us, just in case there's behaviour I've missed here.

**Comment by drchriscole** [comment]
Thanks for looking into this @mattRedBox. As you say the 'any' format works as expected although the name is pretty unintuitive. The 'Default' option is somewhat surprising for an end user, but is familiar behaviour as developer.

I agree not to mess around with the user's input without confirmation - that's the sort of thing I have Excel for doing! As a suggestion maybe a message along the lines of "the format is valid, but is resolved as a different date (2023-10-22). Do you want to update your entry?" may help for the 'Default' format.

**Comment by mattRedBox** [comment]
Hi @drchriscole 
Pending next release, fix is in:
- The date format is set to 'any', rather than 'default' on first selecting Type
- On toggling format to 'default' a tooltip warning (which removes itself after a few seconds) appears once to explain how this format behaves.
