### ISSUE TITLE
Silently removes BOMs when writing file

### ISSUE THREAD

**Issue by sizezero** [ODIQueensland/data-curator#847]
A BOM is a three byte code that can optionally begin a utf-8
file. Most tools don’t care but MS Excel and other MS tools are
notoriously bad at reading utf-8 files that are not prefixed with a
BOM.

Comma Chameleon’s behavior is to preserve BOMs. That is, if the CSV
file that was read contained a BOM, it would write a BOM. If the CSV
file that was read did not contain a BOM then the written file would
not contain a BOM. The current data curator behavior seems to be a
regression from Comma Chameleon.

Datacurator seems to always remove BOMs from utf-8 files and never
adds them. Is this intentional?

This issue was tested from an early October 2018 linux build.
commit e479405049bf47a9564d0a6259c6403f32e8edc0

**Comment by mattRedBox** [comment]
Hi @sizezero 
Can you give me an example of where you have opened/saved a file in Data-Curator, and then tried to open in Ms-Excel and you have encountered issues? Unfortunately due to project restrictions, we haven't been given the scope to test this on any Linux builds, only Windows and Mac.

**Comment by sizezero** [comment]
Thanks for responding to all by issues so quickly!

The specific case is when there is a utf-8 file that contains high bit characters (umlauts etc.) and the file does not have a BOM. If you click on the file to open in Windows w/Excel 365Pro  (and Excel is the default for CSV files) then the file format is interpreted as a windows code page and all the high bit characters are garbled. If the file contains a BOM then Excel reads it with no problem. Be sure to test this with Windows Excel. I'm told Mac Excel handles unicode better. If you google BOM and Excel you will find many rants about how bad Excel is at unicode.

The problem with the current data curator is that if it reads a CSV file with a BOM it will always strip it off when it writes it as a CSV file making the file unreadable by Excel.

Attached are two utf-8 CSV files that contain high bit characters. They are identical except that one contains a BOM and one doesn't.

- load test1-bom.csv in Windows Excel; notice the correct umlauts and tilde characters
- open test1-bom.csv in data curator
- do a trivial edit (add a row) and save as CSV; the BOM is silently removed
- load test1-bom.csv in Windows Excel; notice the garbled characters

You may have to check out the github repo in order to get the following files byte-for-byte
[test1-bom.csv](https://github.com/sizezero/csv-editing/blob/master/test1-bom.csv)
[test1-no-bom.csv](https://github.com/sizezero/csv-editing/blob/master/test1-no-bom.csv)

```
# cat test1-bom.csv 
a,b
über,olé
# hexdump -C test1-bom.csv 
00000000  ef bb bf 61 2c 62 0a c3  bc 62 65 72 2c 6f 6c c3  |...a,b...ber,ol.|
00000010  a9 0a                                             |..|
00000012
# hexdump -C test1-no-bom.csv 
00000000  61 2c 62 0a c3 bc 62 65  72 2c 6f 6c c3 a9 0a     |a,b...ber,ol...|
0000000f
```

**Comment by mattRedBox** [comment]
Thanks for the examples, @sizezero .
I've had a look into this and the behaviour appears to be happening on opening, rather than saving.
The csv library we use deliberately removes the BOM when parsing the CSV file on opening. While they do allow for this to be accounted for in a later major release, we are held to the major release number we're on for now due to other libraries we use needing these.

@markwheels, while UTF-8 doesn't need BOM, it does appear in various csv uses outside Data-Curator, and because I think from what I've read is that it is optional or recommended to remove the BOM, rather than 'mandated' as such, it could be there are other incoming documents, which may also have this. I think I can get around our library stripping it out, by adding a property, BOM to any table that has this as a flag for save/saveas, which would then add the BOM back again just before writing to file when saving. That way it doesn't interfere with any other operations within Data-Curator and the saved file includes it back as it came in.

I guess following this, a minor-effort feature add would be for the user to be able to toggle a Package-wide property to toggle this behaviour on/off (either strip or don't strip the BOM)
