### ISSUE TITLE
Fails to save file while editing a cell

### ISSUE THREAD

**Issue by sizezero** [ODIQueensland/data-curator#850]
When editing a cell, hitting a Ctrl+S does nothing but the user may
think that the file was saved. Exiting the editor results in losing the
edits of the current cell with no warning.

The behavior of most spreadsheets when receiving a Ctrl+S from within
a cell edit is to accept the current cell edit and save the file.

This issue was tested from an early October 2018 linux build.
commit e479405049bf47a9564d0a6259c6403f32e8edc0

**Comment by mattRedBox** [comment]
Hi @sizezero 
Atm, the behaviour of the app is to disable Save until 'Save As...' is invoked to ensure the user nominates where to save to. There has also been work on #840 to also ensure that when a user opens a file, that 'Save' is enabled automatically. Does this seem to be the behaviour you are asking about?

**Comment by mattRedBox** [comment]
/remind me to update dependencies in CI  branch then merge back to develop and master every 1 month

**Comment by sizezero** [comment]
This doesn't have anything to do with creating a new file and running "Save As..."

Here is the success behavior that data curator expects
- open a CSV file
- start editing a cell
- **press return** (the cell has completed editing)
- Ctrl+S
- the file is saved with no prompt
- exit the program
- the user's edits have been saved

Here is the problematic behavior
- open a CSV file
- start editing a cell
- **do not press return** (the cell is still being edited)
- Ctrl+S
- the file is **not** saved; there is no indication that the file wasn't saved
- exit the program
- the users last edit is silently lost

This may sound trivial but in testing Comma Chameleon several users failed to save their edits and were surprised at this behavior. A common use case for us is to open a file, change one value, save and exit. Spreadsheets (such as Excel) do not have this behavior and will save the cell that is currently being edited.

**Comment by mattRedBox** [comment]
Hi @sizezero 
Ok yes I think I understand now. Not sure if there's a handsontable setting that changes this, but I guess the enhancement here could be something like: after cell change that doesn't have a blank value, the current cell coords is remembered. Then any event such as Save could have a hook attached which would ensure that if the current cell changed coords was the same as the active cell, the next row is toggled to ensure the last edited cell is persisted.

**Comment by mattRedBox** [comment]
Hi @sizezero , @markwheels 
I've had a look into this and it looks like again this is behaviour controlled by an underlying library. We use handsontable for much of the heavy lifting for holding and present csv data. From what I can see in the community version we use, there doesn't appear to be any existing hooks or options with which to make this more Excel-like as all the hooks that looks like they might do this only fire once the cursor has left the current cell.

However, we had previously coded to account for how state is held when selecting/deselecting. When deselecting a cell, the current value IS persisted. So I think I can do this in a simple way, by going to when the file is about to be saved and:
- deselect the cell just before save (we already hold the current place when toggling fly-out panels)
- re-select the cell again just after the save.
I think that this should solve this issue. @markwheels will need a bit of effort to add some testing for this change to ensure enough of usual use cases covered here.

**Comment by Stephen-Gates** [comment]
@mattRedBox  Tried this and Data Curator hung. Had to Force Quit.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Not sure whatever you experienced is related to this issue. I've done the same and didn't experience any issues. Any chance you could try again?

**Comment by mattRedBox** [comment]
Perhaps it was a sequence of your previous testing? I've tried with the biggest Dataset I have (50 000 rows) and it still appears OK.

**Comment by Stephen-Gates** [comment]
@mattRedBox hung again with a 4x3 table after doing find and replace commands; editing one cell and doing save as.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Still having trouble replicating Data Curator hanging.

However I do see an issue with the menu Find/Replace - seems to be missing a count of 1. This seems to only happen if the Find/Replace is initiated by the main menu. If initiated by the slide out panel buttons (which gets the counter correct), going back to the main menu then is OK. But if started by the main menu, it seems to get the first count wrong. Once this is done, any find/replace doesn't work correctly. 
This incorrect count appears to happen if the cursor is sitting on a recently edited cell only. Which makes me think this has something to do with this issue correction (save file while editing cell). I'm thinking there is logic I've used in the renderer to remember the cell, that isn't being applied when the call is made via RPC from the main menu. @markwheels, I'll presume you want this fixed and will proceed. I'm thinking I can find the cause within half an hour, but otherwise will let you know if I need more time before proceeding further.
It's kinda subtle (perhaps this bug even existed previously) as once the cursor leaves the cell, so if you enter all of your values first, then enter your search/replace text in the slide-out panel, this forces the renderer to leave the table, meaning that it will save the current cell value, and you won't encounter the bug, but go back and enter a new value/edit an existing value, and use the main menu, it appears that the value hasn't been saved, so Find/Replace won't find it. Once the find counter isn't initiated, it won't reset again until you start a new find/replace (to see the counter reset/disappear).


@Stephen-Gates , this was my latest go at replicating what you described.
![image](https://user-images.githubusercontent.com/5482657/60552128-f98a5000-9d70-11e9-9630-7a7e14f7949f.png)

If you could provide more detail for the sequence of what you're doing (screenshot perhaps), might also help, as I'm keen to see if this is also the cause for the 'hang-up' you're seeing @Stephen-Gates

Also could you provide me with basic specs you're using?
Mac versus Windows? OS version. System memory.  -> at minimum would be useful.

**Comment by markwheels** [comment]
Thanks Matt. Yes, that's fine .
Cheers,
Mark.
